### PR TITLE
Add Gemnasium support and update out of date packages.

### PR DESCRIPTION
**Pull request by joestump**
#### What does this PR do?

Adds the Gemnasium badge to README and updates the packages in `package.json` to the latest stable versions.

#### What unit or integration tests does this PR have?

n/a

#### What selenium tests does this PR have?

n/a

#### How should a developer review this?

Check out the badge and look over the new `package.json`.

#### How should this be manually tested?

Run `npm test`.

#### Any background context you want to provide?

n/a

#### What are the relevant tickets?

https://holidayextras.jira.com/browse/UXUI-254

#### Screenshots (if appropriate)

n/a

#### What gif best describes how you feel about this work?

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit, selenium and regression test coverage.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this cross-browser/device for visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've manually checked this work against any dependent systems.
- [x] I've added and updated translations for all supported languages.
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I've checked that there are no negative speed or performance impacts from my work.
- [x] I've added appropriate tracking.
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this.

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

#### Software Tester review
- [ ] I’ve run all the selenium tests locally and they pass.
- [ ] I agree with the test coverage.
- [ ] I've checked for Ruby changes and understand how to deploy if present.

### CODE REVIEW

**Comment by joestump** [comment]
The Gemnasium badge won't turn green until this is merged in.

**Comment by LouisPryer** [comment]
Taking IP/Dev

**Comment by LouisPryer** [comment]
Looks good :+1:

**Comment by jodiedoubleday** [comment]
Taking SE

**Comment by robhuzzey** [comment]
taking SE/DEV

**Comment by robhuzzey** [comment]
+1

**Pull request merged**
