### PR TITLE
Update browserify from 10.2.6 to 11.0.1

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do? (please provide any background)
Updates browserify to the latest version to resolve the dependencies out of date badge

#### What tests does this PR have?
N/A

#### How can be this tested?
```
npm install
grunt docs
```
Play with the docs & check it behaves as you'd expect

#### Screenshots / Screencast
dependencies

#### What gif best describes how you feel about this work?
chicken

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

### CODE REVIEW

**Comment by hxtomprice** [comment]
Taking Dev

**Comment by pmcnr-hx** [comment]
Taking 2nd slot.

**Comment by hxtomprice** [comment]
:+1:

**Comment by pmcnr-hx** [comment]
:+1:

**Pull request merged**
