### PR TITLE
Put on some make up

### PR DESCRIPTION
**Pull request by hxpaul**
#### What does this PR do? (please provide any background)
Adds standardised linting to ui-toolkit and fixes up the linting errors I found along the way
#### What tests does this PR have?
Only linting has been fixed, existing tests all updated
#### How can this be tested?
`npm run lint` and check the ci https://travis-ci.org/holidayextras/ui-toolkit
#### What gif best describes how you feel about this work?
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by robhuzzey** [comment]
+1 from me

**Comment by hx-markterry** [comment]
Can we lint the `grunt` directory too please.

**Comment by hx-markterry** [comment]
great work! all current changes look good

**Comment by lukehansell** [comment]
:+1: love the branch name too

**Pull request merged**
