### PR TITLE
Updated to V0.14.2 React

### PR DESCRIPTION
**Pull request by robhuzzey**
#### What does this PR do? (please provide any background)
Updates the version or ReactJS to V0.14.2 to support future iterations using newly released dependencies.
An interesting "gotcha" I came across with was a few of my tests: https://github.com/facebook/react/issues/4692

#### What tests does this PR have?
The usual unit tests.

#### How can this be tested?
`npm run test`

#### Screenshots / Screencast
N/A

#### What gif best describes how you feel about this work?
I'm fine

#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [ ] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [ ] I’ve checked for coding anti-patterns.
- [ ] I’ve checked for appropriate test coverage.
- [ ] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by hxpaul** [comment]
Taking a review - we need to update everything else to react V0.14.2 asap imo ok lol omg

**Comment by robhuzzey** [comment]
@hxpaul well... it wasn't actually that difficult **gasps**!

**Comment by hxpaul** [comment]
I get a load of warnings now `Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by exports.`

**Comment by lukehansell** [comment]
surely the docs should be updated as well? For instance the examples still use `React.render` instead of `ReactDOM.render`

**Comment by robhuzzey** [comment]
Fair point @hxpaul, should be an easy grep to change that in the tests.

**Comment by robhuzzey** [comment]
@lukehansell I wasn't even aware of that... docs here right? https://facebook.github.io/react/docs/top-level-api.html#react.dom

**Comment by lukehansell** [comment]
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html gives a good overview of things to consider when upgrading. For instance as I mentioned above `react` (building components) and `react-dom` (interacting with existing DOM) are now two packages. There's a few other things (such as warnings now being errors) which may trip us up where they hadn't before...

**Comment by robhuzzey** [comment]
@lukehansell @hxpaul looks like I've covered off all the issues if you wouldn't mind another look & adding some thumbs up please? :)

**Comment by hxpaul** [comment]
:+1:

**Comment by lukehansell** [comment]
:+1:

**Pull request merged**
