### PR TITLE
Weather https

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- We realised our weather fonts and other images could not be served up from HTTPS
- This creates a variable so people can change the path of their assets
- Moves existing weather assets to use this new variable.

#### What tests does this PR have?
None

#### How can this be tested?
- Run `grunt docs`
- Scroll down to the weather component
- Ensure the weather icons are visible and that the fonts are loaded from the same location as in the asset variable

#### Screenshots / Screencast
screen shot 2015-09-30 at 11 36 04

#### What gif best describes how you feel about this work?
Batman

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by jackdcrawford** [comment]
SE :raised_hands:

**Comment by jackdcrawford** [comment]
Looks good, been using this branch on `uxui-sandbox` for demo purposes for a while, fixed https errors we were getting with the font not loading.

:+1:

**Comment by rahulpatel** [comment]
Taking dev review...

**Comment by rahulpatel** [comment]
:+1:

**Pull request merged**
