### PR TITLE
UXUI-204 grunt-release

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do?
Adds build tasks that:
1. Bump version (semver) in git tag & package.json
2. Commit & push all files & tag
3. Build & publish docs to `gh-pages` branch

#### What unit or integration tests does this PR have?
N/A

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Sanity check the code & run the manual steps below

#### How should this be manually tested?
Release a patch from this branch:
```
npm install
grunt release-patch
```
You should see the patch version bumped & the docs dir pushed to `gh-pages`.

I will tidy up the tags after this PR is merged :)

#### Any background context you want to provide?
N/A

#### What are the relevant tickets?
[UXUI-204](https://holidayextras.jira.com/browse/UXUI-204)

#### Screenshots (if appropriate)
console

#### What gif best describes how you feel about this work?
lol

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by HarleyRowland** [comment]
Taking IP

**Comment by jodiedoubleday** [comment]
Taking SE

**Comment by jodiedoubleday** [comment]
:+1:

**Comment by HarleyRowland** [comment]
+1

**Comment by jodiedoubleday** [comment]
The live docs are now broken.. i broke them by following this :cry:

**Comment by Joezo** [comment]
taking se/dev

**Comment by Joezo** [comment]
Had to make a `dist` dir for the build to work, seems to work other than that :)

**Comment by Joezo** [comment]
:+1:

**Pull request merged**
