### PR TITLE
Base size font didn't reference a variable

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- There was a problem while compiling the less in UXUI-335 where a variable was being referenced but didn't exist, this PR ensure the right varable is called.

#### What tests does this PR have?
None

#### How can this be tested?
- Pull the branch and run `grunt less` there less should build with no error
- Now run `grunt docs`

#### Screenshots / Screencast
screen shot 2015-08-18 at 16 59 27

#### What gif best describes how you feel about this work?
DOH

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by GeorgeF72** [comment]
Se/Dev

**Comment by shackpank** [comment]
SE/Guru

**Comment by GeorgeF72** [comment]
Looks good to me :+1:

**Comment by shackpank** [comment]
Works for me _but_ if that `grunt less` task is important CI should be running it?

**Comment by jodiedoubleday** [comment]
@shackpank it should be indeed, `grunt docs` should also be running `grunt less` this is something we will be fixing in our next release

**Pull request merged**
