### PR TITLE
UXUI-228 - Added Travis-CI with Jest and eslint.

### PR DESCRIPTION
**Pull request by joestump**
#### What does this PR do?

* Adds a `.travis.yml` file that is configured to run tests and lint checking.
* Added [Jest](https://facebook.github.io/jest/) and wired it into `npm test`.
* Added [eslint](http://eslint.org/) and wired it into `npm run lint`.

#### How should a developer review this?

    $ npm run lint && npm test

#### How should this be manually tested?

Same as above.

#### What are the relevant tickets?

https://holidayextras.jira.com/browse/UXUI-228

#### Screenshots (if appropriate)

n/a

#### What gif best describes how you feel about this work?

---
#### Quality checklist (for PR author to complete BEFORE code review):

- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate Selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by jackdcrawford** [comment]
I'll take dev

**Comment by joestump** [comment]
This hasn't been fully tested yet. Travis refuses to acknowledge this repo exists yet. Can we create a work in progress tag so people know to ignore PRs that aren't 100% yet?



—Joe Stump
@joestump

http://stu.mp

**Comment by jackdcrawford** [comment]
Looks good, however JS within jsx files doesn't seem to get linted? I assumed that's what this setting would achieve?
```json
"ecmaFeatures": {
  "jsx": true
}
```

**Comment by joestump** [comment]
No it does. All that does is make sure JSX templates don't throw basic lint errors. 



—Joe Stump
@joestump

http://stu.mp

**Comment by joestump** [comment]
@jackdcrawford this is ready for final review. @dancork would you mind taking a look from an IP point of view? (Or pass it off to an IP who's interested in CI/DevOps and tooling?)

**Comment by joestump** [comment]
@jackdcrawford One more thing; should I go through and remove the `package.json` and `preprocessor.js` files from each of the component folders? I'm 99.9% sure there's no need for the `preprocessor.js`, but not sure about `package.json` and sub-components. My vote is we remove this until individual components are strongly needed on their own.

**Comment by LouisPryer** [comment]
Taking IP/Dev

**Comment by LouisPryer** [comment]
Tests are passing although I am seeing 
```Warning: Failed propType: Required prop `rating` was not specified in `exports`.
Warning: Failed propType: Required prop `image` was not specified in `exports`.
Warning: Failed propType: Required prop `title` was not specified in `exports`.``` every time I run the tests, are these expected?

**Comment by joestump** [comment]
Jodie fixed those in another PR. Once that's merged and this is up to date with master they should be gone. They existed before this PR and weren't introduced by this PR. 



—Joe Stump
@joestump

http://stu.mp

**Comment by LouisPryer** [comment]
Okay awesome, I will leave the +1 until that PR is merged in here but everything else looks good

**Comment by jackdcrawford** [comment]
Picking this up again now

**Comment by jackdcrawford** [comment]
@joestump you're right, if we're not initially going with standalone components then the `preprocessor` & `package.json` are redundant. This also means that the `dev/` folders & `npm` build tasks are too though?

:+1:  for this PR

**Comment by shackpank** [comment]
Will pick up last review (SE/Guru) here

**Comment by shackpank** [comment]
+1

**Comment by LouisPryer** [comment]
+1

**Comment by jodiedoubleday** [comment]
@joestump I don't think my PR should hold this one up, I'm nearly there with that anyway. I think get this up to date with master then get it live :+1:

**Pull request merged**
