### PR TITLE
UXUI-239 - Rename some files and remove styles from components and place into docs

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- We originally decided to add some margin to some of our components when two of the same component are next to one another, however in practical use this causes more headaches than it should, so we have removed the styles from the component and just added them to the docs.
- I have renames `justified_button` component to sit with other components using a `-`

#### What tests does this PR have?
None

#### How can be this tested?
- Check the code for anti-patterns
- run `grunt docs` and check thats the example work as intended (button, flag and justified button)

#### Screenshots / Screencast
screen shot 2015-07-21 at 13 57 13

#### What gif best describes how you feel about this work?
css
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

### CODE REVIEW

**Comment by hxtomprice** [comment]
Taking Dev

**Comment by hxtomprice** [comment]
:+1:

**Comment by hxpaul** [comment]
taking se

**Comment by hxpaul** [comment]
:+1:

**Pull request merged**
