### PR TITLE
Update to latest version of babel and remove node version

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- Updates to Babel 6
- Removes the engine dependencies from package.json
- Changes CI tooling to use 5.1 or latest stable version

#### What tests does this PR have?
None

#### How can this be tested?
Delete the UIToolkit from you machine then clone it again. If you don't do this it will unfortunately fail to build.
`npm install`
`npm run docs`
check the docs looks as good and work as well as they do on ui-toolkit.com
You will have no console errors

#### Screenshots / Screencast
None

#### What gif best describes how you feel about this work?
Babelfish

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [ ] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by elliottcrush** [comment]
Had some issues installing, 'turning it off and on again' seemed to work though. Looks good :+1:

**Comment by Joezo** [comment]
Reviewing this

**Comment by Joezo** [comment]
Followed all the steps and still got an error when building :(

```
Running "shell:docsBuild" (shell) task

> ui-toolkit-docs@0.0.0 build /Users/joe.warren/repos/ui-toolkit/docs
> ./scripts/build.sh

Building docs
Error: Cannot find module 'babel-runtime/helpers/to-consumable-array' from '/Users/joe.warren/repos/ui-toolkit/node_modules/react-a11y/dist'
```

**Comment by hxpaul** [comment]
you have conflicts here

**Comment by hxpaul** [comment]
Also I get the same error as Joe when trying to build
```
Cannot find module 'babel-runtime/helpers/to-consumable-array' from '/Users/paul.clarke/work/ui-toolkit/node_modules/react-a11y/dist'
```
error in the ui-toolkit-docs I think rather than the ui-toolkit

**Pull request closed without merging**
