### PR TITLE
Stricter linting for React/JSX

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do? (please provide any background)
I ran across an issue with our `eslint` setup where it forced us to remove our
```javascript
var React = require('react');
```
from our component templates as it was _defined but never used_:
```
src/components/flag/code/templates/flagTemplate.jsx
  1:4  error  React is defined but never used  no-unused-vars

src/components/icon-list/code/templates/IconListComponentTemplate.jsx
  1:4  error  React is defined but never used  no-unused-vars

src/components/icon-list-item/code/templates/IconListItemComponentTemplate.jsx
  1:4  error  React is defined but never used  no-unused-vars

src/components/image/code/templates/imageTemplate.jsx
  1:4  error  React is defined but never used  no-unused-vars

src/components/tile/code/templates/tileTemplate.jsx
  1:4  error  React is defined but never used  no-unused-vars
```

Whereas it does need to be there when using JSX as once it compiles to JS, the JSX tags convert to `React.createElement`.

I've also added some extra rules, taken from [this gist](https://gist.github.com/nkbt/9efd4facb391edbf8048), that will help to make our JSX & React more robust.

#### What tests does this PR have?
Linting, no unit tests required

#### How can be this tested?
```
npm run lint
```

#### Screenshots / Screencast
N/A

#### What gif best describes how you feel about this work?
boom
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [ ] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [ ] I’ve checked for coding anti-patterns.
- [ ] I’ve checked for appropriate test coverage.
- [ ] I’ve run all the tests locally and they pass.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

### CODE REVIEW

**Comment by jackdcrawford** [comment]
cc @joestump

**Comment by lukehansell-hx** [comment]
:+1: from me

**Comment by manifestinteractive** [comment]
@jackdcrawford .eslintrc is supposed to be a JSON config file. It is currently malformed because of the existing comments and comma after the last variable.  While it's not technically breaking anything, I would hate for this to become an issue in future versions because of an invalid JSON format.

Other than that, everything is perfect :)

**Comment by manifestinteractive** [comment]
:+1:  from me

**Comment by joestump** [comment]
@manifestinteractive & @jackdcrawford It is common across JS tooling to allow comments in JSON configuration files. [eslint](http://eslint.org/docs/user-guide/configuring.html#comments-in-configuration-files) specifically allows this as does NPM in `package.json` files. There's a [JSON5](http://json5.org) standard that some people use that also allows it.

Long story short, it's an established pattern in the JS community.

**Comment by manifestinteractive** [comment]
Good to know @joestump.  I've always been concerned about this as even the developers on the projects that created the JSON config files use comments in them. To me that's not true JSON ( which they say we should use ), and I was always concerned that one day that was going to backfire horribly if they ever forced valid JSON markup in future versions.  But if you don't thing we need to care about it, I will let it go for future project / commits.

**Pull request merged**
