### PR TITLE
stop creating docs every time this is required

### PR DESCRIPTION
**Pull request by hxpaul**
#### What does this PR do? (please provide any background)
removes the post install step setting up docs - this does not need to run every time this repo is required
https://github.com/holidayextras/ui-toolkit/issues/77
#### What tests does this PR have?
none
#### How can this be tested?
npm install this branch see that it is faster
#### What gif best describes how you feel about this work?
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by hx-markterry** [comment]
looks good to me

**Comment by lukehansell** [comment]
:+1:

**Comment by Joezo** [comment]
Can you add this script as one i can run using npm? `npm run docs`, it's still useful. Agreed it's a pain on post install though :)

**Comment by hx-markterry** [comment]
the building of the docs is covered in the readme so i didnt feel there was a need to create another script

**Comment by Joezo** [comment]
ok

**Comment by lukehansell** [comment]
I agree with Joe, this could be easily covered by an npm task to standardise interactions with the repo...

**Comment by hxpaul** [comment]
it's no problem to add one, I'm not sure how this task ties in with the grunt tasks that also cover docs though

**Comment by hxpaul** [comment]
just spotted that `npm docs` opens up the homepage https://github.com/holidayextras/ui-toolkit
have added `npm run docs`

**Pull request merged**
