### PR TITLE
Add data mixin to input

### PR DESCRIPTION
**Pull request by dancork**
#### What does this PR do? (please provide any background)
Add the react data attributes mixin to the input component

#### What tests does this PR have?
Added unit test

#### How can this be tested?
This was a copy of functionality from the button component. Check the code makes sense, the unit test should be enough to verify it is working.

#### What gif best describes how you feel about this work?

---

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [x] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by samsmarthx** [comment]
Looks good to me (3) :+1:

**Comment by jackdcrawford** [comment]
Reviewing :mag:

**Comment by robhuzzey** [comment]
Looks good to me :+1: (1)

**Comment by jackdcrawford** [comment]
:+1: Nice work

**Pull request merged**
