### PR TITLE
UXUI-249 commit dist files to use in other projects

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do?
Adds a distributable built file to this repository so that a consuming project doesn't have to run the build steps on that side.

#### What unit or integration tests does this PR have?
N/A

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Check that `dist/toolkit.css` & `dist/ui-toolkit.standalone.js` are there

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
When [adding the toolkit to the Trip App](https://github.com/holidayextras/tripapplite/pull/2695) I realised that having to build the standalone there was a pain.

#### What are the relevant tickets?
[UXUI-249](https://holidayextras.jira.com/browse/UXUI-249)

#### Screenshots (if appropriate)
N/A

#### What gif best describes how you feel about this work?
net

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit, selenium and regression test coverage.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this cross-browser/device for visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've manually checked this work against any dependent systems.
- [x] I've added and updated translations for all supported languages.
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I've checked that there are no negative speed or performance impacts from my work.
- [x] I've added appropriate tracking.
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this.

#### IP or Developer Review:
- [ ] I agree with the assumptions made in the quality checklist.
- [ ] I’ve witnessed the work behaving as expected.
- [ ] I’ve run all the tests locally and they pass.
- [ ] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [ ] I agree with the assumptions made in the quality checklist.
- [ ] I’ve witnessed the work behaving as expected.
- [ ] I’ve run all the tests locally and they pass.
- [ ] I’ve checked for appropriate test coverage.
- [ ] I’ve checked for coding anti-patterns.
- [ ] I don’t believe this work introduces unnecessary technical debt.
- [ ] +1 from me!

#### Software Tester Selenium review:
- [ ] I’ve run all the tests locally and they pass.
- [ ] I agree with the test coverage.

### CODE REVIEW

**Comment by jodiedoubleday** [comment]
SE taken

**Comment by michaelcarter** [comment]
Shotgun SE/Guru

**Comment by HarleyRowland** [comment]
Taking IP review

**Comment by HarleyRowland** [comment]
+1

**Comment by jodiedoubleday** [comment]
:+1:

**Comment by michaelcarter** [comment]
I'm fine with this yo. Might be worth including a `.min.` uglified version too, but not a huge priority right now as tripapp will minify anyway after inclusion.

**Comment by jackdcrawford** [comment]
I've raised a Jira for this @michaelcarter, not immediately obvious how to pair the reactify & uglify goodness. Will come back to this https://holidayextras.jira.com/browse/UXUI-255.

**Pull request merged**
