### PR TITLE
UXUI-243 add build-dist grunt task to be used in tripapplite

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do?
Updates standalone file name to `ui-toolkit.standalone.js` (same as hapi-sdk)
Adds `grunt build-dist` command

#### What unit or integration tests does this PR have?
N/A

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Run `grunt build-dist`, it should create `./dist/ui-toolkit.standalone.js`

#### How should this be manually tested?
Same as above

#### Any background context you want to provide?
tripapplite uses `requirejs` & therefore can't require the `src/` directory as `browserify` would, a standalone file is required.

#### What are the relevant tickets?
[UXUI-243](https://holidayextras.jira.com/browse/UXUI-243)

#### Screenshots (if appropriate)
N/A

#### What gif best describes how you feel about this work?
grunt

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by HarleyRowland** [comment]
Taking IP review

**Comment by rahulpatel** [comment]
Taking SE/Dev review...

**Comment by hxjamesmcneil** [comment]
Taking SE/Guru

**Comment by rahulpatel** [comment]
Works as expected, it's not minified though (I guess the application using the component can take care of that). :+1:

**Comment by HarleyRowland** [comment]
+1

**Comment by hxjamesmcneil** [comment]
+1

**Pull request merged**
