### PR TITLE
Added new problem to troubleshooting

### PR DESCRIPTION
**Pull request by robhuzzey**
Hope this makes sense... speak to me if not & help me word this better please :)

### CODE REVIEW

**Comment by Joezo** [comment]
Have you got a code example that caused this problem huzz and an example of "solution" you've used?

It'd be great to have a generic snippet of code we can run to replicate the problem.

**Comment by robhuzzey** [comment]
I considered adding a code example but it was too much code.

Basically, the "basic example" on this page http://react-bootstrap.github.io/components.html#navbars in a component causes it to break.

**Comment by jodiedoubleday** [comment]
Looks good to add, I would like you to put this to the REACT Bootstrap guys as well. see if they know a fix

**Comment by robhuzzey** [comment]
When I can some time, I will test this again as since adding this I've learnt a bit more about React & think this could be an issue with how I implemented it?

If not, I will raise the issue with the React Bootstrap guys.

**Pull request closed without merging**
