### PR TITLE
package.json so we can publish anchor, button, image + input

### PR DESCRIPTION
**Pull request by hxpaul**
#### What does this PR do? (please provide any background)

Adds package.json to four components so we can publish them.
Only these components to start with because they are required by other components. When these are published we can change the others (for example tile) to require them from npm, then we get rid of all of the cross directory requires, so then we can publish everything and require it independently.
#### What tests does this PR have?

It is only a config change, no tests
#### How can this be tested?

`cd src/components/anchor && npm install`
#### What gif best describes how you feel about this work?
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.
#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.
#### Software Engineer or project guru review:
- [ ] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [ ] I’ve checked for coding anti-patterns.
- [ ] I’ve checked for appropriate test coverage.
- [ ] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by jameshhx** [comment]
Taking :one:

**Comment by jameshhx** [comment]
Looks good to me :+1:

**Comment by jameshhx** [comment]
Only comment would be that the GIT URLs point to the base project of 'ui-toolkit'. Should we point to the components location within the GIT repo?

**Comment by hxpaul** [comment]
Thanks for looking, is that even possible though? The repository field should link to a repo, not an individual file or folder

**Comment by jameshhx** [comment]
Not sure - it was just a comment out of curiosity as much as anything. I'd personally find it a bit confusing, if an npm module linked to a repo, where the link was not directly to the module in question.

**Pull request closed without merging**
