### PR TITLE
ATOMIC - Update the docs to split stuff into atomic design principles

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- We will be following Brad Frosts [Atomic Design](http://bradfrost.com/blog/post/atomic-web-design/) principles, which means we need to clearly distinguish our atoms and molecules in the UI-Toolkit.
- This has meant changing the NAV on the right and re-organising our components
- I have removed Justified container from the Toolkit as this doesn't fit with the atomic design principles

#### What tests does this PR have?
None (just updated names)

#### How can this be tested?
run `grunt docs` and and take a look at the way the components are laid out in the docs provided, Check that everything under the ATOMS header fits in with its [description](http://bradfrost.com/blog/post/atomic-web-design/#atoms) and that everything under the MOLECULES header fits in with it [description](http://bradfrost.com/blog/post/atomic-web-design/#molecules)

#### Screenshots / Screencast
screen shot 2015-09-14 at 10 01 07

#### What gif best describes how you feel about this work?
Atomic

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by pmcnr-hx** [comment]
Taking 2nd slot.

**Comment by pmcnr-hx** [comment]
I'm not sure about the icon list being classified as an atom... Or if the icon list is actually an atom, it seems some molecules should then also be atoms.

**Comment by jodiedoubleday** [comment]
You are right @pmcnr-hx i want to change the icon list to just be a list and an icon (atoms) like the example on http://demo.patternlab.io/ then an icon list be a molecule (comprising of the two)

**Comment by pmcnr-hx** [comment]
If that's an action item, then all good from me: :+1:

**Comment by cameronviner** [comment]
Taking DEV

**Comment by cameronviner** [comment]
Looks good :+1:

**Pull request merged**
