### PR TITLE
UXUI-78 - Adding styling for inputs

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- We have a few PR's in now to add or use input into the toolkit. These have been created but don't look particularly great.

#### What tests does this PR have?
None

#### How can be this tested?
- Run the UI toolkit 
- `grunt docs` is your best bet, edit the HTML in dev tools and add an input to the page `<input type="text" />` for example
- check ho it looks - not great
- add `class="component-input"` to the input
 It should no look good.

#### Screenshots / Screencast
Input

#### What gif best describes how you feel about this work?
Input
(it makes me sad that a lot of HX developers wont understand this GIF)
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

### CODE REVIEW

**Comment by robhuzzey** [comment]
Taking SE/DEV

**Comment by robhuzzey** [comment]
Looking at this at first glance, it looked like quite  a few files were changed but they are actually auto generated (`dist/ui-toolkit.standalone.js` as an example).

I've reviewed the `less` files but I'd suggest removing the auto-generated files from the repo, stick them on `.gitignore` as they are not really part of the codebase.

**Comment by robhuzzey** [comment]
+1 from me

**Comment by jackdcrawford** [comment]
Yes sir :+1:

**Pull request merged**
