### PR TITLE
PATCH - Update browserify

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- Updates brwoserify from 11.0.1 -> 11.1.0

#### What tests does this PR have?
- None

#### How can this be tested?
- Run `grunt docs`
- You shouldn't see if issues with browserify

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by cameronviner** [comment]
Taking DEV

**Comment by pmcnr-hx** [comment]
Taking 2nd slot.

**Comment by pmcnr-hx** [comment]
:+1: :shipit:

**Comment by cameronviner** [comment]
Looks good :+1:

**Pull request merged**
