### PR TITLE
fixing the responsive images in docs

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- The responsive images component went live last week, however the images on the docs were broken.
- This replaces the broken links with a CDN fronted set of images

#### What tests does this PR have?
None

#### How can this be tested?
run `grunt docs` and scroll down to images, you should see a very cute :panda_face:

#### Screenshots / Screencast
screen shot 2015-10-08 at 14 41 28

#### What gif best describes how you feel about this work?

Pan-dog

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by hxpaul** [comment]
taking

**Comment by hxpaul** [comment]
this change is all :+1: but the original work doesn't do exactly as I expect. If I load the docs full size I see full image, then resize to mobile view and shift and refresh I still see the full size image. If restart my docs server when I'm on mobile size, then I do see the small image.

**Comment by jodiedoubleday** [comment]
If your browser has already downloaded the large image (from being on desktop) and cached it then it will always show the full high quality image regardless of the screen size you are on.

So as an example if you shrink down to mobile and clear cache you will get the small image. As you make the browser bigger you will get the larger images, shrink it back down the mobile and you will still see the larger images as they have already been downloaded and cached.

**Comment by jackdcrawford** [comment]
Review :raised_hands:

**Comment by jackdcrawford** [comment]
:+1:

**Pull request merged**
