### PR TITLE
remove getComponentClasses

### PR DESCRIPTION
**Pull request by hxpaul**
#### What does this PR do? (please provide any background)
Removes getComponentClasses() from the repo - we can just use `classNames` directly to do the same thing.
This is the first step towards publishing these components individually, we need to get rid of the dependencies on other folders in this repo. Anything to get the size of the repo down is good, we remove some dependencies this way, installation is faster and smaller, everyone's a winner.
#### What tests does this PR have?
No new tests, all existing tests select by class with `TestUtils.findRenderedDOMComponentWithClass` and they all still run, sweet!
#### How can this be tested?
Checkout the docs `npm run docs` is everything still looking as you expect?
#### What gif best describes how you feel about this work?
---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by cameronviner** [comment]
Taking DEV

**Comment by cameronviner** [comment]
Looks good to me :+1:

**Comment by HeinBehrenshx** [comment]
taking se

**Comment by HeinBehrenshx** [comment]
:+1:

**Pull request merged**
