### PR TITLE
Adding href & data attributes to image

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do? (please provide any background)
There have already been a few cases where we want to be able to pass an `href` into the `Image` component, this adds that functionality by wrapping the image in an anchor if an `href` is passed in as a prop.

This also adds the [react-data-attributes-mixin](https://github.com/holidayextras/react-data-attributes-mixin).

#### What tests does this PR have?
Updated the image tests to support the `href` wrapping in an anchor logic

#### How can this be tested?
```
git checkout img-href
grunt docs
```
* Navigate to [http://localhost:4000/#image](http://localhost:4000/#image)
* Inspect the element, you should see a single `` element
* Open the editor with "show code"
* Add an `href` attribute to the example
* Inspect the element again, you should see it wrapped in an `<a /> element
* Add a `data` attribute & inspect the element to see the data attributes

#### Screenshots / Screencast
a > img

#### What gif best describes how you feel about this work?
catz

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by nickine** [comment]
Taking SE/Dev

**Comment by nickine** [comment]
All good

**Comment by jodiedoubleday** [comment]
Taking SE

**Comment by jodiedoubleday** [comment]
I've made a slight change to the LESS in this file as the styling was slightly broken due to changing where the class is on the image or its anchor.
@jackdcrawford @nickine can you check you guys are happy with this.

**Comment by jackdcrawford** [comment]
Works for me @jodiedoubleday :+1:

**Comment by jodiedoubleday** [comment]
:+1: from me

**Comment by nickine** [comment]
+1

**Pull request merged**
