### PR TITLE
Published to npmjs.org

### PR DESCRIPTION
**Pull request by msaspence**
#### What does this PR do? (please provide any background)

Bumps the version to 0.29.1, moves the build script to republish rather than post install, updates the name with the hx namespace and updates the documentation to that affect.

#### What gif best describes how you feel about this work?

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by elliottcrush** [comment]
How does this deploy to npm? I can see the prebulish section but no ENV variables on Circle for NPM

**Comment by msaspence** [comment]
@elliottcrush no continuous deployment yet, but this is an improvement that we can iterate on
(I know we talked about this, but added to here for posterity)

Are you happy to +1 now?

**Comment by elliottcrush** [comment]
:+1:

**Comment by jackdcrawford** [comment]
:two: :mag:

**Comment by jackdcrawford** [comment]
:+1:

**Pull request merged**
