### PR TITLE
UXUI-205 Adding docs for tile

### PR DESCRIPTION
**Pull request by jackdcrawford**
#### What does this PR do?
Adds a basic tile component that accepts an `image`, `title` and optional children.

#### What unit or integration tests does this PR have?
N/A

#### What selenium tests does this PR have?
N/A

#### How should a developer review this?
Check that the code seems sane and that the documentation describes sufficiently how to use it.
`grunt docs` will build the docs for you to see the example etc.

#### How should this be manually tested?
Run `grunt docs` & check the example [http://localhost:4000](http://localhost:4000)

#### Any background context you want to provide?
N/A

#### What are the relevant tickets?
[UXU-205](https://holidayextras.jira.com/browse/UXUI-205)

#### Screenshots (if appropriate)
tile

#### What gif best describes how you feel about this work?
tile_gif

---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've checked there is appropriate selenium test coverage.
- [x] I've included regression tests for any bug fixes.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this on mobile Android, Safari, Chrome for any visual changes.
- [x] I've tested this on desktop IE9/10/11, Firefox, Chrome for any visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've added and updated translations for all supported languages
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this

#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!

#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!

#### Software Engineer or project guru review:
- [ ] I agree with the assumptions made in the quality checklist.
- [ ] I’ve witnessed the work behaving as expected.
- [ ] I’ve run all the tests locally and they pass.
- [ ] I’ve checked for appropriate test coverage.
- [ ] I’ve checked for coding anti-patterns.
- [ ] I don’t believe this work introduces unnecessary technical debt.
- [ ] +1 from me!

### CODE REVIEW

**Comment by nickine** [comment]
I'll take the se/dev review

**Comment by jodiedoubleday** [comment]
SE/Guru = Me

**Comment by nickine** [comment]
Looks good to me.

**Comment by jodiedoubleday** [comment]
:+1:

**Comment by LouisPryer** [comment]
Taking IP/Dev review

**Comment by LouisPryer** [comment]
:+1:

**Pull request merged**
