### PR TITLE
UXUI-335 - Variables for _all_the_things_

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
In order to give the UI-Toolkit flexibility and allow it to be used with other popular frameworks like Bootstrap, we need to give people the flexibility of adjusting certain styles to suit their brand needs.
This PR creates a `_variables.less` file which is one single place for all unique adjustments to be made.
The rest of the toolkit will use these variables.

#### What tests does this PR have?
None, tests already exist for all components, these should all continue to pass

#### How can this be tested?
Manual testing is the easiest and most thorough.
You will need to compare the docs at http://www.ui-toolkit.com with the docs produced when you run `grunt docs` on this branch. They should look fairly similar.

#### What gif best describes how you feel about this work?
Dominoes

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by pmcnr-hx** [comment]
Taking 2nd slot.

**Comment by pmcnr-hx** [comment]
All looks good: (and replacing magic values with meaningful constants, even in CSS, is always a good thing!): :+1:

**Comment by LouisPryer** [comment]
Taking Dev

**Comment by LouisPryer** [comment]
Looks good :+1:

**Pull request merged**
