### PR TITLE
Removed React Intl as not production ready

### PR DESCRIPTION
**Pull request by robhuzzey**
#### What does this PR do? (please provide any background)
Removes react intl from the basket item... it's just not going to work as it's too bleeding edge & not production ready :(

#### What tests does this PR have?
Unit tests

#### How can this be tested?
`npm run test`

#### Screenshots / Screencast
N/A

#### What gif best describes how you feel about this work?
disappointed

---

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by hxpaul** [comment]
taking slot :one:

**Comment by hxpaul** [comment]
there is an error now, is that yours? run docs and see

Warning: Failed propType: Invalid prop `children` of type `array` supplied to `exports`, expected `string`.

it means you can't click the links in your basket item

**Comment by robhuzzey** [comment]
@hxpaul afraid that's on master.... not my error.

**Comment by hxpaul** [comment]
Nice all working again now :+1:

**Comment by lukehansell** [comment]
:+1:

**Pull request merged**
